(ns server.logging-min-level-test
  "Guards the namespace noise floors that `server.logging/init-logging!` sets.

   Telemere's `set-min-level!` is generated by encore's signal API with
   sf-arity 4, so its two-argument form is [kind min-level]. A call such as
   (set-min-level! \"xtdb.*\" :warn) therefore reads the pattern as a signal
   KIND and registers a floor that nothing ever emits: the intended namespace
   floor silently never applies. Only the three-argument form with a nil kind
   filters by namespace.

   The mistake is invisible to inspection -- both forms return without error
   and both leave an entry in `get-filters` -- so it is asserted
   behaviourally: emit from a matching namespace and check whether a probe
   handler sees the signal."
  (:require [clojure.test :refer [deftest is testing]]
            [server.logging :as logging]
            [taoensso.telemere :as t]
            [taoensso.telemere.impl :as impl]))

(defn- with-restored-telemere
  "Calls `f`, then puts Telemere's filter and handler roots back as they were.

   Reaches for the impl vars deliberately: `set-min-level!` and `add-handler!`
   write var ROOTS, so wrapping the calls in `with-min-level` / `with-handler`
   would install thread bindings that shadow those writes instead of receiving
   them. Saving and restoring the roots is the only way to exercise the real
   functions without leaking state into the rest of the suite."
  [f]
  (let [saved-filter   (.getRawRoot #'impl/*rt-call-filter*)
        saved-handlers (.getRawRoot #'impl/*sig-handlers*)]
    (try
      (f)
      (finally
        (alter-var-root #'impl/*rt-call-filter* (constantly saved-filter))
        (alter-var-root #'impl/*sig-handlers* (constantly saved-handlers))))))

(defn- emit-info-from
  "Emits one :info signal whose call-site ns is `ns-str`.

   Telemere stamps the call-site namespace at macroexpansion time, so the
   namespace has to be in place when the `log!` form is compiled -- hence
   `binding *ns*` plus `eval` rather than a runtime argument."
  [ns-str]
  (binding [*ns* (create-ns (symbol ns-str))]
    (refer-clojure)
    (eval '(taoensso.telemere/log! {:level :info
                                    :id    :server.logging-min-level-test/probe
                                    :msg   "probe"}))))

(def ^:private noisy
  ["org.eclipse.jetty.probe" "xtdb.probe" "malli.probe"])

(def ^:private quiet "server.probe")

(def ^:private all-probed (conj noisy quiet))

(defn- namespaces-surviving
  "Runs `install-floors!` with only a capturing probe handler registered,
   emits one :info signal from each probed namespace, and returns the set of
   namespaces whose signal was not filtered out."
  [install-floors!]
  (let [captured (atom [])]
    (with-restored-telemere
      (fn []
        (t/with-handler :probe
          (fn ([] nil) ([sig] (swap! captured conj (:ns sig))))
          {:async nil}
          (do
            (install-floors!)
            (doseq [n all-probed] (emit-info-from n))))))
    (set @captured)))

(deftest two-arity-set-min-level-does-not-filter-by-namespace
  (testing "the pattern is read as a signal kind, so every namespace still logs"
    (is (= (set all-probed)
           (namespaces-surviving
            (fn []
              (t/set-min-level! :trace)
              (t/set-min-level! "org.eclipse.jetty.*" :warn)
              (t/set-min-level! "xtdb.*" :warn)
              (t/set-min-level! "malli.*" :warn))))
        "two-arity floors must be shown ineffective, else the fix proves nothing"))

  (testing "the pattern lands in the kind-keyed min-level map"
    (with-restored-telemere
      (fn []
        (t/set-min-level! :info)
        (t/set-min-level! "xtdb.*" :warn)
        (is (= :warn (get-in (t/get-filters) [:runtime :min-level "xtdb.*"]))
            "a kind entry beside :default, not a namespace rule")))))

(deftest three-arity-set-min-level-filters-by-namespace
  (testing "a nil kind plus a pattern drops :info from matching namespaces"
    (is (= #{quiet}
           (namespaces-surviving
            (fn []
              (t/set-min-level! :trace)
              (t/set-min-level! nil "org.eclipse.jetty.*" :warn)
              (t/set-min-level! nil "xtdb.*" :warn)
              (t/set-min-level! nil "malli.*" :warn))))
        "only the unmatched namespace should survive the :warn floor")))

(deftest init-logging-applies-the-library-floors
  (testing "the floors init-logging! installs actually silence the libraries"
    (is (= #{quiet} (namespaces-surviving logging/init-logging!))
        "init-logging! must leave Jetty, XTDB and Malli at :warn")))
