events {}
http {
  server {
    listen 4443 ssl;
    server_name fhir.local;
    ssl_certificate     /etc/nginx/certs/fhir.local.pem;
    ssl_certificate_key /etc/nginx/certs/fhir.local-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / {
      proxy_pass http://hydra:4444;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
    }
  }
}
